### ISSUE TITLE
Parsing VBI captions from SMPTE ST 436 track in MXF wrapper 

### ISSUE THREAD

**Issue by plondino** [MediaArea/MediaInfoLib#2029] opened 2023-06-22 16:29 UTC
I have an SD MXF MPEG2 file (720x480) with captions in a ST 436 VBI track as well as the ATSC A/53 in the MPEG2 video stream.  MediaInfo shows two text tracks:

```
Text MediaArea/MediaInfo#1
Count                                    : 305
Count of stream of this kind             : 2
Kind of stream                           : Text
Kind of stream                           : Text
Stream identifier                        : 0
Stream identifier                        : 1
Inform                                   : EIA-608 (A/53 / DTVCC Transport)
ID                                       : 2-CC1
ID                                       : 2-CC1
Format                                   : EIA-608
Format                                   : EIA-608
Commercial name                          : EIA-608
Muxing mode                              : A/53 / DTVCC Transport
Bit rate mode                            : CBR
Bit rate mode                            : Constant
Delay                                    : 3540003
Delay                                    : 59 min 0 s
Delay                                    : 59 min 0 s 3 ms
Delay                                    : 59 min 0 s
Delay                                    : 00:59:00.003
Delay                                    : 00:59:00.003
Delay, origin                            : Container
Delay, origin                            : Container
Delay relative to video                  : 0
Delay relative to video                  : 00:00:00.000
Delay relative to video                  : 00:00:00.000
Stream size                              : 0
Stream size                              : 0.00 Byte (0%)
Stream size                              :  Byte0
Stream size                              : 0.0 Byte
Stream size                              : 0.00 Byte
Stream size                              : 0.000 Byte
Stream size                              : 0.00 Byte (0%)
Proportion of this stream                : 0.00000
Title                                    : Picture
Type of the first event                  : PopOn
Caption service name                     : CC1

Text MediaArea/MediaInfo#2
Count                                    : 304
Count of stream of this kind             : 2
Kind of stream                           : Text
Kind of stream                           : Text
Stream identifier                        : 1
Stream identifier                        : 2
ID                                       : 9
ID                                       : 9
Duration                                 : 1482181
Duration                                 : 24 min 42 s
Duration                                 : 24 min 42 s 181 ms
Duration                                 : 24 min 42 s
Duration                                 : 00:24:42.181
Duration                                 : 00:24:42;05
Duration                                 : 00:24:42.181 (00:24:42;05)
Frame rate                               : 29.970
Frame rate                               : 29.970 FPS
Frame count                              : 44421
Delay                                    : 3540003
Delay                                    : 59 min 0 s
Delay                                    : 59 min 0 s 3 ms
Delay                                    : 59 min 0 s
Delay                                    : 00:59:00.003
Delay                                    : 00:59:00;02
Delay                                    : 00:59:00.003 (00:59:00;02)
Delay_DropFrame                          : Yes
Delay, origin                            : Container
Delay, origin                            : Container
Delay relative to video                  : 0
Delay relative to video                  : 00:00:00.000
Delay relative to video                  : 00:00:00;00
Delay relative to video                  : 00:00:00.000 (00:00:00;00)
Title                                    : Auxiliary Data
```

The VBI text track is missing any stream information. My understanding is that captions in VBI are essentially 608, so there should be `Format` and `Caption service name` data since there could be multiple streams (CC1-CC4) in the VBI data.  I don't have the tools to extract/validate the VBI so it's not 100% clear to me if this is a limitation of MediaInfo or if there is something missing in the caption data in the stream.  I will attach a single VBI packet and can make a sample file available for further investigation.

MXF ST 436 tracks with CDP packets in an Ancillary Data wrapping work as expected.

**Comment by JeromeMartinez** [comment] 2024-04-29 18:19
@plondino @joe-sciame-wm we added the decoding of VBI for both [Line 21](https://en.wikipedia.org/wiki/EIA-608) & [VITC](https://en.wikipedia.org/wiki/Vertical_interval_timecode). Only payload sample coding 4 (= 8-bit luma) is implemented because this is the only value we find in files we have.

With you sample frame it leads to:

```
Other #3
ID                                       : 2-12
Format                                   : SMPTE TC
Muxing mode                              : VBI / VITC
Duration                                 : 30 s 30 ms
Bit rate mode                            : Constant
Frame rate                               : 29.970 FPS
Time code of first frame                 : 00:59:00;02
Title                                    : Auxiliary Data

Other #4
ID                                       : 2-14
Format                                   : SMPTE TC
Muxing mode                              : VBI / VITC
Duration                                 : 30 s 30 ms
Bit rate mode                            : Constant
Frame rate                               : 29.970 FPS
Time code of first frame                 : 00:59:00;02
Title                                    : Auxiliary Data
```

608 captions are detected for both fields but nothing is displayed by default due to the value of the CC (0x8080 = void) but it should be something like (with a file I have):

```
Text #1
ID                                       : 2-21-CC1
Format                                   : EIA-608
Muxing mode                              : VBI / Line 21
Duration                                 : 1 min 5 s
Bit rate mode                            : Constant
Frame rate                               : 29.970 FPS
Stream size                              : 0.00 Byte (0%)
Count of events                          : 41
Count of PopOn events                    : 2
Count of RollUp events                   : 38
Count of PaintOn events                  : 1
Count of lines                           : 39
Maximum count of lines per event         : 3
Count of frames before first event       : 55
Type of the first event                  : PopOn

Text #2
ID                                       : 2-21-CC3
Format                                   : EIA-608
Muxing mode                              : VBI / Line 21
Duration                                 : 1 min 5 s
Bit rate mode                            : Constant
Frame rate                               : 29.970 FPS
Stream size                              : 0.00 Byte (0%)
Count of lines                           : 0
```

About the ID: first value is the MXF ID, 2nd value is the VBI line number (field 1 & field 2 are merged), 3rd value for caption is the CC service (CC1-CC4, T1-T4).

[Dev snapshots](https://mediaarea.net/download/snapshots/binary/) contain this update.
Please test on your files because we have only few files with that on our side.

**Closed** 2024-04-29 18:19 UTC

**Comment by plondino** [comment] 2024-06-06 02:26
This seems to be working on a few files I have, in that it's parsing the text stream as CC1 and the VBI timecode is being picked up. 

I do notice a few differences from what's displayed above:

- Muxing mode is `VBI` for both text and timecode, rather than `VBI / Line 21` and `VBI / VITC` respectively
- I am not seeing any of the `Count of` metadata fields as above. 

Also, Switch does display that the file has a "Line 284: CEA-608" which I would guess is CC3 but I am assuming there is no valid caption data there and that's why MediaInfo is not displaying it.

<img width="684" alt="vbi" src="https://github.com/MediaArea/MediaInfoLib/assets/40502255/e90dd595-4f86-42a5-a66f-32e91a343cd5">

Full payloads (24.01 and 24.05) attached.

[389HR.mxf.24.01.1.xml.txt](https://github.com/user-attachments/files/15598823/389HR.mxf.24.01.1.xml.txt)
[389HR.mxf.xml.txt](https://github.com/user-attachments/files/15598824/389HR.mxf.xml.txt)

**Comment by FranceBB** [comment] 2024-06-06 11:52
It seems to be working on all my samples. :D
Here's a dual language one with Italian on page 777 and English on page 778 being correctly recognized as:

`
General 
Complete name : Test1.mxf 
Format : MXF 
Format version : 1.2 
Format profile : OP-1a 
Format settings : Closed / Complete 
File size : 16.9 GiB 
Duration : 2 h 5 min 
Overall bit rate : 19.2 Mb/s 
Frame rate : 25.000 FPS 
Encoded date : 2021-04-01 01:00:59.744 
Writing application : Omneon Inc. Omneon Media Subsystem 6.4.1.0.1 
Writing library : Omneon Media Api (windows) 

Video 
ID : 2 
Format : MPEG Video 
Format version : Version 2 
Format profile : Main@Main 
Format settings : BVOP 
Format settings, BVOP : Yes 
Format settings, Matrix : Default 
Format settings, GOP : M=3, N=12 
Format settings, picture structure : Frame 
Format settings, wrapping mode : Frame 
Codec ID : 0D01030102046101-0401020201011100 
Duration : 2 h 5 min 
Bit rate mode : Constant 
Bit rate : 12.0 Mb/s 
Width : 720 pixels 
Height : 576 pixels 
Display aspect ratio : 4:3 
Original display aspect ratio : 16:9 
Frame rate : 25.000 FPS 
Standard : PAL 
Color space : YUV 
Chroma subsampling : 4:2:0 
Bit depth : 8 bits 
Scan type : Interlaced 
Scan order : Top Field First 
Compression mode : Lossy 
Bits/(Pixel*Frame) : 1.157 
Time code of first frame : 00:00:00:00 
Time code source : Group of pictures header 
GOP, Open/Closed : Closed 
Stream size : 10.5 GiB (62%) 
Color range : Limited 

Audio #1 
ID : 4 
Format : PCM 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Codec ID : 0D01030102060100 
Duration : 2 h 5 min 
Bit rate mode : Constant 
Bit rate : 2 304 kb/s 
Channel(s) : 2 channels 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 24 bits 
Stream size : 2.02 GiB (12%) 
Language : Italian 
Locked : Yes 

Audio #2 
ID : 6-1 
Format : Dolby E 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Muxing mode : SMPTE ST 337 
Codec ID : 0D01030102060100 
Duration : 2 h 5 min 
Bit rate mode : Constant 
Bit rate : 1 291 kb/s 
Channel(s) : 6 channels 
Channel layout : L C Ls X R LFE Rs X 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 20 bits 
Delay relative to video : -9 h 59 min 
Stream size : 1.13 GiB (7%) 
Title : UCN11804_HD_TO_SD-Interle_Prog0 
Language : Italian (DE) 
AC-3 metadata : Yes 
 Bit rate : 384 kbps 
 Service kind : Complete Main 
 Channel layout : L R C LFE Ls Rs 
 Dialog Normalization : -24 dB 
 RF (compr) profile : Film Standard 
 Line (dynrng) profile : Film Standard 
 cmixlev : -3.0 dB 
 surmixlev : -3 dB 
 mixlevel : 105 dB 
 roomtyp : Large 
 dmixmod : Lo/Ro 
 ltrtcmixlev : -3.0 dB 
 ltrtsurmixlev : -3.0 dB 
 lorocmixlev : -3.0 dB 
 lorosurmixlev : -3.0 dB 
 hpfon : Yes 
 bwlpfon : Yes 
 lfelpfon : Yes 
 sur90on : Yes 
 suratton : No 
 rfpremphon : No 
GuardBand_Before : 771 
GuardBand_After : 1188 
Locked : Yes 

Audio #3 
ID : 6-2 
Format : Dolby E 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Muxing mode : SMPTE ST 337 
Codec ID : 0D01030102060100 
Duration : 2 h 5 min 
Bit rate mode : Constant 
Bit rate : 505 kb/s 
Channel(s) : 2 channels 
Channel layout : X X X L X X X R 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 20 bits 
Delay relative to video : -9 h 59 min 
Stream size : 454 MiB (3%) 
Title : UCN11804_HD_TO_SD-Interle_Prog1 
Language : Italian (DE) 
AC-3 metadata : Yes 
 Bit rate : 192 kbps 
 Service kind : Complete Main 
 Channel layout : L R 
 Dialog Normalization : -24 dB 
 RF (compr) profile : Film Standard 
 Line (dynrng) profile : Film Standard 
 cmixlev : -3.0 dB 
 surmixlev : -3 dB 
 ltrtcmixlev : -3.0 dB 
 ltrtsurmixlev : -3.0 dB 
 lorocmixlev : -3.0 dB 
 lorosurmixlev : -3.0 dB 
 hpfon : Yes 
 bwlpfon : Yes 
 lfelpfon : Yes 
 sur90on : Yes 
 suratton : No 
 rfpremphon : No 
GuardBand_Before : 771 
GuardBand_After : 1188 
Locked : Yes 

Audio #4 
ID : 7 
Format : PCM 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Codec ID : 0D01030102060100 
Duration : 2 h 5 min 
Bit rate mode : Constant 
Bit rate : 2 304 kb/s 
Channel(s) : 2 channels 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 24 bits 
Stream size : 2.02 GiB (12%) 
Language : Oriya 
Locked : Yes 

Text #1 
ID : 8-16-777 
Format : Teletext Subtitle 
Muxing mode : VBI 
Duration : 2 h 5 min 
Frame rate : 25.000 FPS 

Text #2 
ID : 8-16-778 
Format : Teletext Subtitle 
Muxing mode : VBI 
Duration : 2 h 5 min 
Frame rate : 25.000 FPS 

Other #1 
ID : 1-Material 
Type : Time code 
Format : MXF TC 
Frame rate : 25.000 FPS 
Time code of first frame : 10:00:00:00 
Time code of last frame : 12:05:37:13 
Time code settings : Material Package 
Time code, stripped : Yes 

Other #2 
ID : 1-Source 
Type : Time code 
Format : MXF TC 
Frame rate : 25.000 FPS 
Time code of first frame : 10:00:00:00 
Time code of last frame : 12:05:37:13 
Time code settings : Source Package 
Time code, stripped : Yes 
`


Same goes for an even older movie transferred from BetaCAM and then softsubbed with Cavena:

```
General 
Complete name : Test2.mxf
Format : MXF 
Format version : 1.2 
Format profile : OP-1a 
Format settings : Closed / Complete 
File size : 12.1 GiB 
Duration : 1 h 30 min 
Overall bit rate : 19.2 Mb/s 
Frame rate : 25.000 FPS 
Encoded date : 2014-03-09 15:38:40.040 
Writing application : Omneon Inc. Omneon Media Subsystem 6.4.1.0.1 
Writing library : Omneon Media Api (windows) 

Video 
ID : 2 
Format : MPEG Video 
Format version : Version 2 
Format profile : Main@Main 
Format settings : CustomMatrix / BVOP 
Format settings, BVOP : Yes 
Format settings, Matrix : Custom 
Format settings, GOP : M=3, N=15 
Format settings, picture structure : Frame 
Format settings, wrapping mode : Frame 
Codec ID : 0D01030102046101-0401020201011100 
Duration : 1 h 30 min 
Bit rate mode : Constant 
Bit rate : 12.0 Mb/s 
Width : 720 pixels 
Height : 576 pixels 
Display aspect ratio : 4:3 
Frame rate : 25.000 FPS 
Standard : PAL 
Color space : YUV 
Chroma subsampling : 4:2:0 
Bit depth : 8 bits 
Scan type : Interlaced 
Scan order : Top Field First 
Compression mode : Lossy 
Bits/(Pixel*Frame) : 1.157 
Time code of first frame : 09:59:59:12 
Time code source : Group of pictures header 
GOP, Open/Closed : Closed 
Stream size : 7.58 GiB (62%) 
Color range : Limited 

Audio #1 
ID : 4 
Format : PCM 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Codec ID : 0D01030102060100 
Duration : 1 h 30 min 
Bit rate mode : Constant 
Bit rate : 2 304 kb/s 
Channel(s) : 2 channels 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 24 bits 
Stream size : 1.45 GiB (12%) 
Language : Italian 
Locked : Yes 

Audio #2 
ID : 6-1 
Format : Dolby E 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Muxing mode : SMPTE ST 337 
Codec ID : 0D01030102060100 
Duration : 1 h 30 min 
Bit rate mode : Constant 
Bit rate : 1 291 kb/s 
Channel(s) : 6 channels 
Channel layout : L C Ls X R LFE Rs X 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 20 bits 
Stream size : 835 MiB (7%) 
Title : SMF16018_3_Prog0 
Language : Italian (DE) 
AC-3 metadata : Yes 
 Service kind : Complete Main 
 Channel layout : L R C LFE Ls Rs 
 Dialog Normalization : -24 dB 
 RF (compr) profile : Film Standard 
 Line (dynrng) profile : Film Standard 
 cmixlev : -3.0 dB 
 surmixlev : -3 dB 
 dmixmod : Lt/Rt 
 ltrtcmixlev : -3.0 dB 
 ltrtsurmixlev : -3.0 dB 
 lorocmixlev : -3.0 dB 
 lorosurmixlev : -3.0 dB 
 hpfon : Yes 
 bwlpfon : Yes 
 lfelpfon : Yes 
 sur90on : Yes 
 suratton : Yes 
 rfpremphon : No 
GuardBand_Before : 771 
GuardBand_After : 1188 
Locked : Yes 

Audio #3 
ID : 6-2 
Format : Dolby E 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Muxing mode : SMPTE ST 337 
Codec ID : 0D01030102060100 
Duration : 1 h 30 min 
Bit rate mode : Constant 
Bit rate : 505 kb/s 
Channel(s) : 2 channels 
Channel layout : X X X L X X X R 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 20 bits 
Stream size : 326 MiB (3%) 
Title : SMF16018_3_Prog1 
Language : Italian (DE) 
AC-3 metadata : Yes 
 Service kind : Complete Main 
 Channel layout : L R 
 Dialog Normalization : -24 dB 
 RF (compr) profile : Film Standard 
 Line (dynrng) profile : Film Standard 
 cmixlev : -3.0 dB 
 surmixlev : -3 dB 
 mixlevel : 101 dB 
 dmixmod : Lt/Rt 
 ltrtcmixlev : -3.0 dB 
 ltrtsurmixlev : -3.0 dB 
 lorocmixlev : -3.0 dB 
 lorosurmixlev : -3.0 dB 
 hpfon : Yes 
 bwlpfon : Yes 
 lfelpfon : No 
 sur90on : No 
 suratton : No 
 rfpremphon : No 
GuardBand_Before : 771 
GuardBand_After : 1188 
Locked : Yes 

Audio #4 
ID : 7 
Format : PCM 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Codec ID : 0D01030102060100 
Duration : 1 h 30 min 
Bit rate mode : Constant 
Bit rate : 2 304 kb/s 
Channel(s) : 2 channels 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 24 bits 
Stream size : 1.45 GiB (12%) 
Language : Oriya 
Locked : Yes 

Text #1 
ID : 8-16-777 
Format : Teletext Subtitle 
Muxing mode : VBI 
Duration : 1 h 30 min 
Frame rate : 25.000 FPS 

Text #2 
ID : 8-16-778 
Format : Teletext Subtitle 
Muxing mode : VBI 
Duration : 1 h 30 min 
Frame rate : 25.000 FPS 

Other #1 
ID : 1-Material 
Type : Time code 
Format : MXF TC 
Frame rate : 25.000 FPS 
Time code of first frame : 10:00:00:00 
Time code of last frame : 11:30:22:03 
Time code settings : Material Package 
Time code, stripped : Yes 

Other #2 
ID : 1-Source 
Type : Time code 
Format : MXF TC 
Frame rate : 25.000 FPS 
Time code of first frame : 10:00:00:00 
Time code of last frame : 11:30:22:16 
Time code settings : Source Package 
Time code, stripped : Yes 


```


Looks good. :)

**Comment by JeromeMartinez** [comment] 2024-06-06 12:07
> Muxing mode is VBI for both text and timecode, rather than VBI / Line 21 and VBI / VITC respectively

In the meanwhile we changed our mind and don't show "Line 21" or "VITC" anymore, it seems not so useful (only one way to mux 608 or time code in VBI).

> I am not seeing any of the Count of metadata fields as above.

With the file you sent by email, I have the following content if I activate full parsing:

```
Count of events                          : 445
Count of PopOn events                    : 445
Count of lines                           : 733
Maximum count of lines per event         : 3
Count of frames before first event       : 1811
Type of the first event                  : PopOn
```

for both CC1 in MPEG Video stream and CC1 in VBI.
Count of frames before first event is not listed in default parsing because it is too far away and we catch CC1 when we probe the middle of the file, so we don't know when it begins.

> Also, Switch does display that the file has a "Line 284: CEA-608" which I would guess is CC3 but I am assuming there is no valid caption data there and that's why MediaInfo is not displaying it.

We synchronize with second field but we don't show CC3 or CC4 because it is empty.

**Comment by JeromeMartinez** [comment] 2024-06-06 12:08
> Same goes for an even older movie transferred from BetaCAM and then softsubbed with Cavena:

@FranceBB would you mind to share such file, in private if needed?
We don't have many files with Teletext and we would like to have more of them for regression tests.

**Comment by FranceBB** [comment] 2024-06-24 06:50
@JeromeMartinez  no problem, there you go: https://we.tl/t-egjpJ6AHI4
(link lasts 7 days, valid until June 30th 2024)

I had to trim it to 13 minutes 'cause WeTransfer only allows 2GB. If you need the untrimmed source, send me your email in private and I'll send you a faspex. Also apologies for the daly but I've been hammered with things and I completely forgot about this.

It's an MPEG-2 anamorphic flagged as 16:9 with CH.1-2 PCM Stereo Italian, CH.3-4 DolbyE 5.1 Italian + 2.0 Original, CH.5-6 Stereo Original. The TTX are Italian at page 777 and Original at page 778. Being an American movie in this case the "Original" language is "English". 

Mediainfo is correctly identifying both subtitles, the only "funny" thing is that we generally flag the language as "ITA" for Italian and "ORI" for "Original" 'cause when it goes on air and it's played out via Omneon, re-encoded live by an hardware encoder, coupled in the multiplexer and beamed to hotbird, the user at home can choose "Italian" or "Original" on every content. If the content is natively Italian, then of course Original will also be Italian, otherwise it's gonna be whatever the original language of that content is (English, French, German etc). This is done by flagging the language with ommq as a proprietary piece of metadata called ovn_trackmatch. Funnily enough, Mediainfo recognizes it but thinks that "ORI" stands for "Oriya", an Indian language. :P I'm sure it's trying to check for iso codes or something and matches that. It's not a problem, I just found it to be funny.

General 
Complete name : A:\MEDIA\temp\Honey_SD_16x9_MPEG2_PCM_DolbyE_PCM_TTXNUORI_Trim.mxf 
Format : MXF 
Format version : 1.3 
Format profile : OP-1a 
Format settings : Closed / Complete 
File size : 1.79 GiB 
Duration : 13 min 20 s 
Overall bit rate : 19.2 Mb/s 
Frame rate : 25.000 FPS 
Encoded date : 2024-06-24 06:37:50.660 
Writing application : Omneon Inc. Omneon Media Subsystem 10.0.0.0.1 
Writing library : Omneon Media Api (windows) 

Video 
ID : 2 
Format : MPEG Video 
Format version : Version 2 
Format profile : Main@Main 
Format settings : BVOP 
Format settings, BVOP : Yes 
Format settings, Matrix : Default 
Format settings, GOP : M=3, N=15 
Format settings, picture structure : Frame 
Format settings, wrapping mode : Frame 
Codec ID : 0D01030102046001-0401020201011100 
Duration : 13 min 20 s 
Bit rate mode : Constant 
Bit rate : 12.0 Mb/s 
Width : 720 pixels 
Height : 576 pixels 
Display aspect ratio : 16:9 
Frame rate : 25.000 FPS 
Standard : PAL 
Color space : YUV 
Chroma subsampling : 4:2:0 
Bit depth : 8 bits 
Scan type : Interlaced 
Scan order : Top Field First 
Compression mode : Lossy 
Bits/(Pixel*Frame) : 1.157 
Time code of first frame : 10:00:00:00 
Time code source : Group of pictures header 
GOP, Open/Closed : Closed 
Stream size : 1.12 GiB (62%) 
Color range : Limited 
Color primaries : BT.601 PAL 
Transfer characteristics : BT.601 
Matrix coefficients : BT.470 System B/G 

Audio #1 
ID : 4 
Format : PCM 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Codec ID : 0D01030102060100 
Duration : 13 min 20 s 
Bit rate mode : Constant 
Bit rate : 2 304 kb/s 
Channel(s) : 2 channels 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 24 bits 
Stream size : 220 MiB (12%) 
Language : Italian 
Locked : Yes 

Audio #2 
ID : 6-1 
Format : Dolby E 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Muxing mode : SMPTE ST 337 
Codec ID : 0D01030102060100-0402020203021C00 
Duration : 13 min 20 s 
Bit rate mode : Constant 
Bit rate : 1 291 kb/s 
Channel(s) : 6 channels 
Channel layout : L C Ls X R LFE Rs X 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 20 bits 
Stream size : 123 MiB (7%) 
Title : SMF16018_3_Prog0 
Language : Italian (DE) 
AC-3 metadata : Yes 
 Service kind : Complete Main 
 Channel layout : L R C LFE Ls Rs 
 Dialog Normalization : -24 dB 
 RF (compr) profile : Film Standard 
 Line (dynrng) profile : Film Standard 
 cmixlev : -3.0 dB 
 surmixlev : -3 dB 
 dmixmod : Lt/Rt 
 ltrtcmixlev : -3.0 dB 
 ltrtsurmixlev : -3.0 dB 
 lorocmixlev : -3.0 dB 
 lorosurmixlev : -3.0 dB 
 hpfon : Yes 
 bwlpfon : Yes 
 lfelpfon : Yes 
 sur90on : Yes 
 suratton : Yes 
 rfpremphon : No 
GuardBand_Before : 771 
GuardBand_After : 1188 
Locked : Yes 

Audio #3 
ID : 6-2 
Format : Dolby E 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Muxing mode : SMPTE ST 337 
Codec ID : 0D01030102060100-0402020203021C00 
Duration : 13 min 20 s 
Bit rate mode : Constant 
Bit rate : 505 kb/s 
Channel(s) : 2 channels 
Channel layout : X X X L X X X R 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 20 bits 
Stream size : 48.2 MiB (3%) 
Title : SMF16018_3_Prog1 
Language : Italian (DE) 
AC-3 metadata : Yes 
 Service kind : Complete Main 
 Channel layout : L R 
 Dialog Normalization : -24 dB 
 RF (compr) profile : Film Standard 
 Line (dynrng) profile : Film Standard 
 cmixlev : -3.0 dB 
 surmixlev : -3 dB 
 mixlevel : 101 dB 
 dmixmod : Lt/Rt 
 ltrtcmixlev : -3.0 dB 
 ltrtsurmixlev : -3.0 dB 
 lorocmixlev : -3.0 dB 
 lorosurmixlev : -3.0 dB 
 hpfon : Yes 
 bwlpfon : Yes 
 lfelpfon : No 
 sur90on : No 
 suratton : No 
 rfpremphon : No 
GuardBand_Before : 771 
GuardBand_After : 1188 
Locked : Yes 

Audio #4 
ID : 7 
Format : PCM 
Format settings : Little 
Format settings, wrapping mode : Frame (BWF) 
Codec ID : 0D01030102060100 
Duration : 13 min 20 s 
Bit rate mode : Constant 
Bit rate : 2 304 kb/s 
Channel(s) : 2 channels 
Sampling rate : 48.0 kHz 
Frame rate : 25.000 FPS (1920 SPF) 
Bit depth : 24 bits 
Stream size : 220 MiB (12%) 
Language : Oriya 
Locked : Yes 

Text #1 
ID : 8-16-777 
Format : Teletext Subtitle 
Muxing mode : VBI 
Duration : 13 min 20 s 
Frame rate : 25.000 FPS 

Text #2 
ID : 8-16-778 
Format : Teletext Subtitle 
Muxing mode : VBI 
Duration : 13 min 20 s 
Frame rate : 25.000 FPS 

Other #1 
ID : 1-Material 
Type : Time code 
Format : MXF TC 
Frame rate : 25.000 FPS 
Time code of first frame : 10:00:00:00 
Time code of last frame : 10:13:19:24 
Time code settings : Material Package 
Time code, stripped : Yes 

Other #2 
ID : 1-Source 
Type : Time code 
Format : MXF TC 
Frame rate : 25.000 FPS 
Time code of first frame : 10:00:00:00 
Time code of last frame : 10:13:19:24 
Time code settings : Source Package 
Time code, stripped : Yes 

Other #3 
ID : SystemScheme1-0-0 
Type : Time code 
Format : SMPTE TC 
Muxing mode : System scheme 1 
Time code of first frame : 10:00:00:00 



On the other hand, that's the only Omneon proprietary metadata that it identifies 'cause everything else is not recognized (and I don't expect it to, given that they're proprietary metadata in the container).
Using ommq -ldata we can see them all:

ommq.exe -ldata "A:\MEDIA\temp\Honey_SD_16x9_MPEG2_PCM_DolbyE_PCM_TTXNUORI_Trim.mxf"
A:\MEDIA\temp\Honey_SD_16x9_MPEG2_PCM_DolbyE_PCM_TTXNUORI_Trim.mxf: 25 FPS, 5 tracks, 20000 frames (0-20000)
  def in/out=0/20000, precharge=0, first frame=0, tc=10:00:00.00
  clipProperties=, umid=0x060A2B340101010501010D231300AF1C7CD54DBDB5121F1E9CD0D1197170DBDA, afd=0xff
  media 0: \\mibctvan000\Ingest\MEDIA\temp\Honey_SD_16x9_MPEG2_PCM_DolbyE_PCM_TTXNUORI_Trim.mxf
  track 0: 8-bit lgop mpeg video,16:9,4:2:0,12.0Mbit
  track 1: 24-bit 2-channel,  little-endian,,none,2.3Mbit
  track 2: 24-bit 2-channel,  little-endian,,none,2.3Mbit
  track 3: 24-bit 2-channel,  little-endian,,none,2.3Mbit
  track 4: 8-bit 436Vbi,,none,294.0Kbit
movie user data:
  0: ovn_creation=D4_01314H0(Dir4 Release 6.4.1.3-12021711 (release_6_4_1));SD_MXF_R21;local_10.64.28.234:1340;Tap1P9817/8;vitc19_21;/fs0/clip.dir/SMF16018.mxf;generic;in:0 out:135554;10/26/2012 07:30:34;vbi148000
  1: sky_loudnesscorrected=true
  2: sky_loudnesscorrect_sys=DP600
  3: sky_loudnesscorrect_date=31-10-2012 08:36:04
  4: SE-Omneon=File 770 10198318-09032014163816_TTX.mxf built on MIBCFBS01 at 2014-03-09 16.38.16:797
  track 0:
    0: ovn_arcmode=anamorphic
  track 1:
    0: ovn_trackmatch=ITA
  track 2:
    0: ovn_trackmatch=ITA-DE
  track 3:
    0: ovn_trackmatch=ORI




Let me know if you need anything else and as always I'm happy to help. :)

**Comment by JeromeMartinez** [comment] 2024-06-24 08:15
Mostly out of topic because it is about MXf metadata, no need to read if you are interested in only VBI.

@FranceBB 

> @JeromeMartinez no problem, there you go

Thank you.

>  WeTransfer only allows 2GB.

E.g. gofile.io does not have this limitation, but I don't need more.

> CH.3-4 DolbyE 5.1 Italian + 2.0 Original

Using DE for "Dolby E" in the language tag where it is expected to be the country code, hmmm... ;-)
So Italian from Germany :).
And as far as I know the MXF descriptive metadata does not permit to describe the different languages in the Dolby E services, so both Dolby E services are flagged Italian :(.

> CH.5-6 Stereo Original. 

ORI is the ISO language code for something else, and if we change that we wouldn't conform to the specs... So it will stay Oriya :).

> The TTX are Italian at page 777 and Original at page 778. Being an American movie in this case the "Original" language is "English".

We don't parse (yet, but as it is old I doubt we'll ever do) Teletext so no readout of language even if it is in the teletext stream :(.

> This is done by flagging the language with ommq as a proprietary piece of metadata called ovn_trackmatch. 

No idea about `ovn_trackmatch` but on my side I find such metadata in standard MXF Descriptive Metadata segment.

The file contains Omneon private metadata but no idea if language metadata in duplicated there, or if there is something else interesting, well, it is hidden (I have no Omneon doc :( ).

Anyway, thank you for the file, I add it to my test repository.

**Comment by FranceBB** [comment] 2024-06-25 13:39
Yeah well I inherited those when I got here in 2016 as they were introduced in 2006 by other people, so... yeah, ITA, ITA-DE and ORI. :P
