### ISSUE TITLE
Saving Metadata Changes to a WAV file from CLI

### ISSUE THREAD

**Issue by kt-lowen** [MediaArea/MediaInfoLib#1574] opened 2022-08-15 19:32 UTC
Hi Folks,

Less of an issue and more of a question (I am new to using this).

I am currently trying to adjust the time reference for my audio file using the CLI, and I have managed to change the time reference to the desired time, however I am unable to actually save this metadata (or cannot figure out what commands I need to use to accomplish this.) After I change the time reference and look at the core data using:

```
bwfmetaedit.exe --specialchars --out-core my_file.WAV 
```
I get this output:
```
FileName,Description,Originator,OriginatorReference,OriginationDate,OriginationTime,TimeReference (translated),TimeReference,BextVersion,UMID,LoudnessValue,LoudnessRange,MaxTruePeakLevel,MaxMomentaryLoudness,MaxShortTermLoudness,CodingHistory,IARL,IART,ICMS,ICMT,ICOP,ICRD,IENG,IGNR,IKEY,IMED,INAM,IPRD,ISBJ,ISFT,ISRC,ISRF,ITCH
my_file.WAV,,,,,,17:07:40.000,2959680001,0,,,,,,,,,,,,,,,,,,,,,Lavf59.16.100,,
```
Which is great (and what I want), but now I am unsure how to move forward with saving this change to the file, the commands I have tried don't seem to actually save these changes.

Any help would be hugely appreciated, thanks so much!

**Comment by JeromeMartinez** [comment] 2022-08-16 09:01
Duplicate of https://github.com/MediaArea/BWFMetaEdit/issues/234 (and it is better to talk about BWF MetaEdit on BWF MetaEdit issue tracker).

**Closed by JeromeMartinez** 2022-08-16 09:01 UTC
