### ISSUE TITLE
MediaInfo and FFMpeg dissagree on number of audiochannels.

### ISSUE THREAD

**Issue by RensvanderZwan** [MediaArea/MediaInfoLib#2076] opened 2024-06-19 10:40 UTC
For media file: [https://we.tl/t-rCoWScLZfC] , MediaInfo says there are 9 audio channels (6 PCM and 3 Dolby-E) and FFMpeg says there are 8 audiochannels (by lack of a Dolby-E decoder all considers them as PCM).

There is something strange about the streamorder. All Doly-E channels are streamorder 5 and stream 6 is absent. So streamorder is 0,1,2,3,4,5,5,5,7,8.

I am using MediaInfo to set parameters for FFMpeg conversion like audio channels , framerate conversion etc. The conversion fails because of this dissagrement

So who is right? Is there a 'Dark' audio channel?

MediaInfo=24.05.1 / FFMpeg=version 6.1.1-full_build-www.gyan.dev

**Comment by JeromeMartinez** [comment] 2024-06-19 10:50
Duplicate of https://github.com/MediaArea/MediaInfo/issues/874.

**Comment by JeromeMartinez** [comment] 2024-06-19 10:51
> by lack of a Dolby-E decoder all considers them as PCM

This is the source of the disagreement, and FFmpeg does not provide the truth due to that.

> All Doly-E channels are streamorder 5 and stream 6 is absent.

Not absent, it is grouped with StreamOrder 5 for creating the Dolby E stream (StreamOrder 5 is first half of the Dolby E content, StreamOrder 6 is second half of the Dolby E content).

> So who is right? Is there a 'Dark' audio channel?

Both, with different meanings:
- FFmpeg sees PCM
- MediaInfo sees the 2 halves of Dolby E

> The conversion fails because of this dissagrement

Issue here is that `StreamOrder` should be "5 / 6" so you catch that the 2 streams are needed.
We'll update that soon.

**Comment by JeromeMartinez** [comment] 2024-06-19 11:02
> MediaInfo says there are 9 audio channels (6 PCM and 3 Dolby-E)

@RensvanderZwan MediaInfo does not say that.
MediaInfo says there are 14 audio channels in 9 (theoretically) independent streams (6 PCM and 1 6-ch Dolby E and 2 1-ch Dolby E).
My guess is that the 6 pure (not Dolby E) PCM streams are not so independent but there is not metadata indicating that.

**Comment by JeromeMartinez** [comment] 2024-06-21 13:24
[Development snapshots](https://mediaarea.net/download/snapshots/binary/) have this patch.

**Closed** 2024-06-21 13:23 UTC

**Comment by RensvanderZwan** [comment] 2024-06-24 20:09
Thank you for changing the StreamOrder. It is much easier now to isolate the Dolby-E streams from the rest. 

Issue [https://github.com/MediaArea/MediaInfoLib/issues/1846](https://github.com/MediaArea/MediaInfoLib/issues/1846) perfectly describes what needs to be set in FFMpeg with what was found by MediaInfo.
